// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DeploymentTrafficFilterRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final DeploymentTrafficFilterRuleArgs Empty = new DeploymentTrafficFilterRuleArgs();

    /**
     * Azure endpoint GUID. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
     * 
     */
    @Import(name="azureEndpointGuid")
    private @Nullable Output<String> azureEndpointGuid;

    /**
     * @return Azure endpoint GUID. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
     * 
     */
    public Optional<Output<String>> azureEndpointGuid() {
        return Optional.ofNullable(this.azureEndpointGuid);
    }

    /**
     * Azure endpoint name. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
     * 
     */
    @Import(name="azureEndpointName")
    private @Nullable Output<String> azureEndpointName;

    /**
     * @return Azure endpoint name. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
     * 
     */
    public Optional<Output<String>> azureEndpointName() {
        return Optional.ofNullable(this.azureEndpointName);
    }

    /**
     * Description of this individual rule
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description of this individual rule
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Computed rule ID
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return Computed rule ID
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Traffic filter source: IP address, CIDR mask, or VPC endpoint ID, **only required** when the type is not `azurePrivateEndpoint`
     * 
     */
    @Import(name="source")
    private @Nullable Output<String> source;

    /**
     * @return Traffic filter source: IP address, CIDR mask, or VPC endpoint ID, **only required** when the type is not `azurePrivateEndpoint`
     * 
     */
    public Optional<Output<String>> source() {
        return Optional.ofNullable(this.source);
    }

    private DeploymentTrafficFilterRuleArgs() {}

    private DeploymentTrafficFilterRuleArgs(DeploymentTrafficFilterRuleArgs $) {
        this.azureEndpointGuid = $.azureEndpointGuid;
        this.azureEndpointName = $.azureEndpointName;
        this.description = $.description;
        this.id = $.id;
        this.source = $.source;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DeploymentTrafficFilterRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DeploymentTrafficFilterRuleArgs $;

        public Builder() {
            $ = new DeploymentTrafficFilterRuleArgs();
        }

        public Builder(DeploymentTrafficFilterRuleArgs defaults) {
            $ = new DeploymentTrafficFilterRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param azureEndpointGuid Azure endpoint GUID. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder azureEndpointGuid(@Nullable Output<String> azureEndpointGuid) {
            $.azureEndpointGuid = azureEndpointGuid;
            return this;
        }

        /**
         * @param azureEndpointGuid Azure endpoint GUID. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder azureEndpointGuid(String azureEndpointGuid) {
            return azureEndpointGuid(Output.of(azureEndpointGuid));
        }

        /**
         * @param azureEndpointName Azure endpoint name. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder azureEndpointName(@Nullable Output<String> azureEndpointName) {
            $.azureEndpointName = azureEndpointName;
            return this;
        }

        /**
         * @param azureEndpointName Azure endpoint name. Only applicable when the ruleset type is set to `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder azureEndpointName(String azureEndpointName) {
            return azureEndpointName(Output.of(azureEndpointName));
        }

        /**
         * @param description Description of this individual rule
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description of this individual rule
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param id Computed rule ID
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Computed rule ID
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param source Traffic filter source: IP address, CIDR mask, or VPC endpoint ID, **only required** when the type is not `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder source(@Nullable Output<String> source) {
            $.source = source;
            return this;
        }

        /**
         * @param source Traffic filter source: IP address, CIDR mask, or VPC endpoint ID, **only required** when the type is not `azurePrivateEndpoint`
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            return source(Output.of(source));
        }

        public DeploymentTrafficFilterRuleArgs build() {
            return $;
        }
    }

}
