// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.ec.inputs.ElasticsearchProjectLinkedProjectsArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ElasticsearchProjectLinkedArgs extends com.pulumi.resources.ResourceArgs {

    public static final ElasticsearchProjectLinkedArgs Empty = new ElasticsearchProjectLinkedArgs();

    @Import(name="projects", required=true)
    private Output<Map<String,ElasticsearchProjectLinkedProjectsArgs>> projects;

    public Output<Map<String,ElasticsearchProjectLinkedProjectsArgs>> projects() {
        return this.projects;
    }

    /**
     * Status of each linked project, keyed by project ID. Populated by the provider from the API.
     * 
     */
    @Import(name="statuses")
    private @Nullable Output<Map<String,String>> statuses;

    /**
     * @return Status of each linked project, keyed by project ID. Populated by the provider from the API.
     * 
     */
    public Optional<Output<Map<String,String>>> statuses() {
        return Optional.ofNullable(this.statuses);
    }

    private ElasticsearchProjectLinkedArgs() {}

    private ElasticsearchProjectLinkedArgs(ElasticsearchProjectLinkedArgs $) {
        this.projects = $.projects;
        this.statuses = $.statuses;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ElasticsearchProjectLinkedArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ElasticsearchProjectLinkedArgs $;

        public Builder() {
            $ = new ElasticsearchProjectLinkedArgs();
        }

        public Builder(ElasticsearchProjectLinkedArgs defaults) {
            $ = new ElasticsearchProjectLinkedArgs(Objects.requireNonNull(defaults));
        }

        public Builder projects(Output<Map<String,ElasticsearchProjectLinkedProjectsArgs>> projects) {
            $.projects = projects;
            return this;
        }

        public Builder projects(Map<String,ElasticsearchProjectLinkedProjectsArgs> projects) {
            return projects(Output.of(projects));
        }

        /**
         * @param statuses Status of each linked project, keyed by project ID. Populated by the provider from the API.
         * 
         * @return builder
         * 
         */
        public Builder statuses(@Nullable Output<Map<String,String>> statuses) {
            $.statuses = statuses;
            return this;
        }

        /**
         * @param statuses Status of each linked project, keyed by project ID. Populated by the provider from the API.
         * 
         * @return builder
         * 
         */
        public Builder statuses(Map<String,String> statuses) {
            return statuses(Output.of(statuses));
        }

        public ElasticsearchProjectLinkedArgs build() {
            if ($.projects == null) {
                throw new MissingRequiredPropertyException("ElasticsearchProjectLinkedArgs", "projects");
            }
            return $;
        }
    }

}
