// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAzurePrivatelinkEndpointArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAzurePrivatelinkEndpointArgs Empty = new GetAzurePrivatelinkEndpointArgs();

    /**
     * Region to retrieve the Private Link configuration for.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return Region to retrieve the Private Link configuration for.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    private GetAzurePrivatelinkEndpointArgs() {}

    private GetAzurePrivatelinkEndpointArgs(GetAzurePrivatelinkEndpointArgs $) {
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAzurePrivatelinkEndpointArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAzurePrivatelinkEndpointArgs $;

        public Builder() {
            $ = new GetAzurePrivatelinkEndpointArgs();
        }

        public Builder(GetAzurePrivatelinkEndpointArgs defaults) {
            $ = new GetAzurePrivatelinkEndpointArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param region Region to retrieve the Private Link configuration for.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region Region to retrieve the Private Link configuration for.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        public GetAzurePrivatelinkEndpointArgs build() {
            if ($.region == null) {
                throw new MissingRequiredPropertyException("GetAzurePrivatelinkEndpointArgs", "region");
            }
            return $;
        }
    }

}
