// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDeploymentsIntegrationsServerArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetDeploymentsIntegrationsServerArgs Empty = new GetDeploymentsIntegrationsServerArgs();

    /**
     * Overall health status of the resource instances.
     * 
     */
    @Import(name="healthy")
    private @Nullable Output<String> healthy;

    /**
     * @return Overall health status of the resource instances.
     * 
     */
    public Optional<Output<String>> healthy() {
        return Optional.ofNullable(this.healthy);
    }

    /**
     * Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Elastic stack version.
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return Elastic stack version.
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private GetDeploymentsIntegrationsServerArgs() {}

    private GetDeploymentsIntegrationsServerArgs(GetDeploymentsIntegrationsServerArgs $) {
        this.healthy = $.healthy;
        this.status = $.status;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDeploymentsIntegrationsServerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDeploymentsIntegrationsServerArgs $;

        public Builder() {
            $ = new GetDeploymentsIntegrationsServerArgs();
        }

        public Builder(GetDeploymentsIntegrationsServerArgs defaults) {
            $ = new GetDeploymentsIntegrationsServerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param healthy Overall health status of the resource instances.
         * 
         * @return builder
         * 
         */
        public Builder healthy(@Nullable Output<String> healthy) {
            $.healthy = healthy;
            return this;
        }

        /**
         * @param healthy Overall health status of the resource instances.
         * 
         * @return builder
         * 
         */
        public Builder healthy(String healthy) {
            return healthy(Output.of(healthy));
        }

        /**
         * @param status Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param version Elastic stack version.
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Elastic stack version.
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public GetDeploymentsIntegrationsServerArgs build() {
            return $;
        }
    }

}
