// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDeploymentsIntegrationsServer extends com.pulumi.resources.InvokeArgs {

    public static final GetDeploymentsIntegrationsServer Empty = new GetDeploymentsIntegrationsServer();

    /**
     * Overall health status of the resource instances.
     * 
     */
    @Import(name="healthy")
    private @Nullable String healthy;

    /**
     * @return Overall health status of the resource instances.
     * 
     */
    public Optional<String> healthy() {
        return Optional.ofNullable(this.healthy);
    }

    /**
     * Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
     * 
     */
    @Import(name="status")
    private @Nullable String status;

    /**
     * @return Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * Elastic stack version.
     * 
     */
    @Import(name="version")
    private @Nullable String version;

    /**
     * @return Elastic stack version.
     * 
     */
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    private GetDeploymentsIntegrationsServer() {}

    private GetDeploymentsIntegrationsServer(GetDeploymentsIntegrationsServer $) {
        this.healthy = $.healthy;
        this.status = $.status;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDeploymentsIntegrationsServer defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDeploymentsIntegrationsServer $;

        public Builder() {
            $ = new GetDeploymentsIntegrationsServer();
        }

        public Builder(GetDeploymentsIntegrationsServer defaults) {
            $ = new GetDeploymentsIntegrationsServer(Objects.requireNonNull(defaults));
        }

        /**
         * @param healthy Overall health status of the resource instances.
         * 
         * @return builder
         * 
         */
        public Builder healthy(@Nullable String healthy) {
            $.healthy = healthy;
            return this;
        }

        /**
         * @param status Resource kind status. Can be one of `initializing`, `stopping`, `stopped`, `rebooting`, `restarting`.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable String status) {
            $.status = status;
            return this;
        }

        /**
         * @param version Elastic stack version.
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable String version) {
            $.version = version;
            return this;
        }

        public GetDeploymentsIntegrationsServer build() {
            return $;
        }
    }

}
