// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.ec.Utilities;
import com.pulumi.ec.inputs.GetDeploymentArgs;
import com.pulumi.ec.inputs.GetDeploymentPlainArgs;
import com.pulumi.ec.inputs.GetDeploymentsArgs;
import com.pulumi.ec.inputs.GetDeploymentsPlainArgs;
import com.pulumi.ec.inputs.GetStackArgs;
import com.pulumi.ec.inputs.GetStackPlainArgs;
import com.pulumi.ec.outputs.GetDeploymentResult;
import com.pulumi.ec.outputs.GetDeploymentsResult;
import com.pulumi.ec.outputs.GetStackResult;
import java.util.concurrent.CompletableFuture;

public final class EcFunctions {
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud deployment.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetDeploymentResult> getDeployment(GetDeploymentArgs args) {
        return getDeployment(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud deployment.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetDeploymentResult> getDeploymentPlain(GetDeploymentPlainArgs args) {
        return getDeploymentPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud deployment.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetDeploymentResult> getDeployment(GetDeploymentArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ec:index/getDeployment:getDeployment", TypeShape.of(GetDeploymentResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud deployment.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetDeploymentResult> getDeploymentPlain(GetDeploymentPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ec:index/getDeployment:getDeployment", TypeShape.of(GetDeploymentResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetDeploymentsResult> getDeployments() {
        return getDeployments(GetDeploymentsArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetDeploymentsResult> getDeploymentsPlain() {
        return getDeploymentsPlain(GetDeploymentsPlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetDeploymentsResult> getDeployments(GetDeploymentsArgs args) {
        return getDeployments(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetDeploymentsResult> getDeploymentsPlain(GetDeploymentsPlainArgs args) {
        return getDeploymentsPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetDeploymentsResult> getDeployments(GetDeploymentsArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ec:index/getDeployments:getDeployments", TypeShape.of(GetDeploymentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve a list of IDs for the deployment and resource kinds, based on the specified query.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetDeploymentsResult> getDeploymentsPlain(GetDeploymentsPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ec:index/getDeployments:getDeployments", TypeShape.of(GetDeploymentsResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud stack.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetStackResult> getStack(GetStackArgs args) {
        return getStack(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud stack.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetStackResult> getStackPlain(GetStackPlainArgs args) {
        return getStackPlain(args, InvokeOptions.Empty);
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud stack.
     * 
     * ## Example Usage
     * 
     */
    public static Output<GetStackResult> getStack(GetStackArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("ec:index/getStack:getStack", TypeShape.of(GetStackResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Use this data source to retrieve information about an existing Elastic Cloud stack.
     * 
     * ## Example Usage
     * 
     */
    public static CompletableFuture<GetStackResult> getStackPlain(GetStackPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("ec:index/getStack:getStack", TypeShape.of(GetStackResult.class), args, Utilities.withVersion(options));
    }
}
