// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.ec.inputs.SecurityProjectProductTypeArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SecurityProjectArgs extends com.pulumi.resources.ResourceArgs {

    public static final SecurityProjectArgs Empty = new SecurityProjectArgs();

    /**
     * admin features package (BYOK, BYOIDP, CCS, CCR)
     * 
     */
    @Import(name="adminFeaturesPackage")
    private @Nullable Output<String> adminFeaturesPackage;

    /**
     * @return admin features package (BYOK, BYOIDP, CCS, CCR)
     * 
     */
    public Optional<Output<String>> adminFeaturesPackage() {
        return Optional.ofNullable(this.adminFeaturesPackage);
    }

    /**
     * A custom domain label compatible with RFC-1035 standards. Derived from the project name by default.
     * 
     */
    @Import(name="alias")
    private @Nullable Output<String> alias;

    /**
     * @return A custom domain label compatible with RFC-1035 standards. Derived from the project name by default.
     * 
     */
    public Optional<Output<String>> alias() {
        return Optional.ofNullable(this.alias);
    }

    /**
     * Descriptive name for a project.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Descriptive name for a project.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="productTypes")
    private @Nullable Output<List<SecurityProjectProductTypeArgs>> productTypes;

    public Optional<Output<List<SecurityProjectProductTypeArgs>>> productTypes() {
        return Optional.ofNullable(this.productTypes);
    }

    /**
     * Unique human-readable identifier for a region in Elastic Cloud.
     * 
     */
    @Import(name="regionId", required=true)
    private Output<String> regionId;

    /**
     * @return Unique human-readable identifier for a region in Elastic Cloud.
     * 
     */
    public Output<String> regionId() {
        return this.regionId;
    }

    private SecurityProjectArgs() {}

    private SecurityProjectArgs(SecurityProjectArgs $) {
        this.adminFeaturesPackage = $.adminFeaturesPackage;
        this.alias = $.alias;
        this.name = $.name;
        this.productTypes = $.productTypes;
        this.regionId = $.regionId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SecurityProjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SecurityProjectArgs $;

        public Builder() {
            $ = new SecurityProjectArgs();
        }

        public Builder(SecurityProjectArgs defaults) {
            $ = new SecurityProjectArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param adminFeaturesPackage admin features package (BYOK, BYOIDP, CCS, CCR)
         * 
         * @return builder
         * 
         */
        public Builder adminFeaturesPackage(@Nullable Output<String> adminFeaturesPackage) {
            $.adminFeaturesPackage = adminFeaturesPackage;
            return this;
        }

        /**
         * @param adminFeaturesPackage admin features package (BYOK, BYOIDP, CCS, CCR)
         * 
         * @return builder
         * 
         */
        public Builder adminFeaturesPackage(String adminFeaturesPackage) {
            return adminFeaturesPackage(Output.of(adminFeaturesPackage));
        }

        /**
         * @param alias A custom domain label compatible with RFC-1035 standards. Derived from the project name by default.
         * 
         * @return builder
         * 
         */
        public Builder alias(@Nullable Output<String> alias) {
            $.alias = alias;
            return this;
        }

        /**
         * @param alias A custom domain label compatible with RFC-1035 standards. Derived from the project name by default.
         * 
         * @return builder
         * 
         */
        public Builder alias(String alias) {
            return alias(Output.of(alias));
        }

        /**
         * @param name Descriptive name for a project.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Descriptive name for a project.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder productTypes(@Nullable Output<List<SecurityProjectProductTypeArgs>> productTypes) {
            $.productTypes = productTypes;
            return this;
        }

        public Builder productTypes(List<SecurityProjectProductTypeArgs> productTypes) {
            return productTypes(Output.of(productTypes));
        }

        public Builder productTypes(SecurityProjectProductTypeArgs... productTypes) {
            return productTypes(List.of(productTypes));
        }

        /**
         * @param regionId Unique human-readable identifier for a region in Elastic Cloud.
         * 
         * @return builder
         * 
         */
        public Builder regionId(Output<String> regionId) {
            $.regionId = regionId;
            return this;
        }

        /**
         * @param regionId Unique human-readable identifier for a region in Elastic Cloud.
         * 
         * @return builder
         * 
         */
        public Builder regionId(String regionId) {
            return regionId(Output.of(regionId));
        }

        public SecurityProjectArgs build() {
            if ($.regionId == null) {
                throw new MissingRequiredPropertyException("SecurityProjectArgs", "regionId");
            }
            return $;
        }
    }

}
