// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class DeploymentElasticsearchConfig
    {
        public readonly string? DockerImage;
        public readonly ImmutableArray<string> Plugins;
        public readonly string? UserSettingsJson;
        public readonly string? UserSettingsOverrideJson;
        public readonly string? UserSettingsOverrideYaml;
        public readonly string? UserSettingsYaml;

        [OutputConstructor]
        private DeploymentElasticsearchConfig(
            string? dockerImage,

            ImmutableArray<string> plugins,

            string? userSettingsJson,

            string? userSettingsOverrideJson,

            string? userSettingsOverrideYaml,

            string? userSettingsYaml)
        {
            DockerImage = dockerImage;
            Plugins = plugins;
            UserSettingsJson = userSettingsJson;
            UserSettingsOverrideJson = userSettingsOverrideJson;
            UserSettingsOverrideYaml = userSettingsOverrideYaml;
            UserSettingsYaml = userSettingsYaml;
        }
    }
}
