// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class DeploymentElasticsearchTopology
    {
        /// <summary>
        /// Autoscaling policy defining the maximum and / or minimum total size for this topology element. For more information refer to the `autoscaling` block.
        /// </summary>
        public readonly Outputs.DeploymentElasticsearchTopologyAutoscaling? Autoscaling;
        /// <summary>
        /// Elasticsearch settings applied to all topologies unless overridden in the `topology` element.
        /// </summary>
        public readonly ImmutableArray<Outputs.DeploymentElasticsearchTopologyConfig> Configs;
        /// <summary>
        /// Unique topology identifier. It generally refers to an Elasticsearch data tier, such as `hot_content`, `warm`, `cold`, `coordinating`, `frozen`, `ml` or `master`.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Default instance configuration of the deployment template. No need to change this value since Kibana has only one _instance type_.
        /// </summary>
        public readonly string? InstanceConfigurationId;
        public readonly ImmutableArray<string> NodeRoles;
        /// <summary>
        /// The node type for the Elasticsearch cluster (data node).
        /// </summary>
        public readonly string? NodeTypeData;
        /// <summary>
        /// The node type for the Elasticsearch cluster (ingest node).
        /// </summary>
        public readonly string? NodeTypeIngest;
        /// <summary>
        /// The node type for the Elasticsearch cluster (master node).
        /// </summary>
        public readonly string? NodeTypeMaster;
        /// <summary>
        /// The node type for the Elasticsearch cluster (machine learning node).
        /// </summary>
        public readonly string? NodeTypeMl;
        /// <summary>
        /// Amount in Gigabytes per topology element in the `"&lt;size in GB&gt;g"` notation. When omitted, it defaults to the deployment template value.
        /// </summary>
        public readonly string? Size;
        /// <summary>
        /// Type of resource to which the size is assigned. Defaults to `"memory"`.
        /// </summary>
        public readonly string? SizeResource;
        /// <summary>
        /// Number of zones the instance type of the Elasticsearch cluster will span. This is used to set or unset HA on an Elasticsearch node type. When omitted, it defaults to the deployment template value.
        /// </summary>
        public readonly int? ZoneCount;

        [OutputConstructor]
        private DeploymentElasticsearchTopology(
            Outputs.DeploymentElasticsearchTopologyAutoscaling? autoscaling,

            ImmutableArray<Outputs.DeploymentElasticsearchTopologyConfig> configs,

            string id,

            string? instanceConfigurationId,

            ImmutableArray<string> nodeRoles,

            string? nodeTypeData,

            string? nodeTypeIngest,

            string? nodeTypeMaster,

            string? nodeTypeMl,

            string? size,

            string? sizeResource,

            int? zoneCount)
        {
            Autoscaling = autoscaling;
            Configs = configs;
            Id = id;
            InstanceConfigurationId = instanceConfigurationId;
            NodeRoles = nodeRoles;
            NodeTypeData = nodeTypeData;
            NodeTypeIngest = nodeTypeIngest;
            NodeTypeMaster = nodeTypeMaster;
            NodeTypeMl = nodeTypeMl;
            Size = size;
            SizeResource = sizeResource;
            ZoneCount = zoneCount;
        }
    }
}
