// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class DeploymentElasticsearchSnapshotSource
    {
        /// <summary>
        /// Name of the snapshot to restore. Use '**latest_success**' to get the most recent successful snapshot.
        /// </summary>
        public readonly string? SnapshotName;
        /// <summary>
        /// ID of the Elasticsearch cluster that will be used as the source of the snapshot
        /// </summary>
        public readonly string SourceElasticsearchClusterId;

        [OutputConstructor]
        private DeploymentElasticsearchSnapshotSource(
            string? snapshotName,

            string sourceElasticsearchClusterId)
        {
            SnapshotName = snapshotName;
            SourceElasticsearchClusterId = sourceElasticsearchClusterId;
        }
    }
}
