// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class ElasticsearchProjectMetadata
    {
        /// <summary>
        /// Date and time when the project was created.
        /// </summary>
        public readonly string? CreatedAt;
        /// <summary>
        /// ID of the user.
        /// </summary>
        public readonly string? CreatedBy;
        /// <summary>
        /// The Organization ID who owns the project.
        /// </summary>
        public readonly string? OrganizationId;
        /// <summary>
        /// Date and time when the project was suspended.
        /// </summary>
        public readonly string? SuspendedAt;
        /// <summary>
        /// Reason why the project was suspended.
        /// </summary>
        public readonly string? SuspendedReason;

        [OutputConstructor]
        private ElasticsearchProjectMetadata(
            string? createdAt,

            string? createdBy,

            string? organizationId,

            string? suspendedAt,

            string? suspendedReason)
        {
            CreatedAt = createdAt;
            CreatedBy = createdBy;
            OrganizationId = organizationId;
            SuspendedAt = suspendedAt;
            SuspendedReason = suspendedReason;
        }
    }
}
