// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class GetStackElasticsearchResult
    {
        /// <summary>
        /// Maximum size of the instances.
        /// </summary>
        public readonly int CapacityConstraintsMax;
        /// <summary>
        /// Minimum size of the instances.
        /// </summary>
        public readonly int CapacityConstraintsMin;
        /// <summary>
        /// List of node types compatible with this one.
        /// </summary>
        public readonly ImmutableArray<string> CompatibleNodeTypes;
        /// <summary>
        /// List of default plugins.
        /// </summary>
        public readonly ImmutableArray<string> DefaultPlugins;
        /// <summary>
        /// List of configuration options that cannot be overridden by user settings.
        /// </summary>
        public readonly ImmutableArray<string> Denylists;
        /// <summary>
        /// Docker image to use for the Elasticsearch cluster instances.
        /// </summary>
        public readonly string DockerImage;
        /// <summary>
        /// List of available plugins to be specified by users in Elasticsearch cluster instances.
        /// </summary>
        public readonly ImmutableArray<string> Plugins;

        [OutputConstructor]
        private GetStackElasticsearchResult(
            int capacityConstraintsMax,

            int capacityConstraintsMin,

            ImmutableArray<string> compatibleNodeTypes,

            ImmutableArray<string> defaultPlugins,

            ImmutableArray<string> denylists,

            string dockerImage,

            ImmutableArray<string> plugins)
        {
            CapacityConstraintsMax = capacityConstraintsMax;
            CapacityConstraintsMin = capacityConstraintsMin;
            CompatibleNodeTypes = compatibleNodeTypes;
            DefaultPlugins = defaultPlugins;
            Denylists = denylists;
            DockerImage = dockerImage;
            Plugins = plugins;
        }
    }
}
