// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Outputs
{

    [OutputType]
    public sealed class OrganizationMembersProjectObservabilityRole
    {
        /// <summary>
        /// Role applies to all projects in the organization.
        /// </summary>
        public readonly bool? AllProjects;
        /// <summary>
        /// If provided, the user assigned this role assignment will be granted this application role when signing in to the project(s) specified in the role assignment.
        /// </summary>
        public readonly ImmutableArray<string> ApplicationRoles;
        /// <summary>
        /// Role applies to projects listed here.
        /// </summary>
        public readonly ImmutableArray<string> ProjectIds;
        /// <summary>
        /// Assigned role. (Allowed values: `admin`, `editor`, `viewer`)
        /// </summary>
        public readonly string Role;

        [OutputConstructor]
        private OrganizationMembersProjectObservabilityRole(
            bool? allProjects,

            ImmutableArray<string> applicationRoles,

            ImmutableArray<string> projectIds,

            string role)
        {
            AllProjects = allProjects;
            ApplicationRoles = applicationRoles;
            ProjectIds = projectIds;
            Role = role;
        }
    }
}
