// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DeploymentElasticsearchTopologyConfig {
    /**
     * @return List of Elasticsearch supported plugins. Check the Stack Pack version to see which plugins are supported for each version. This is currently only available from the UI and [ecctl](https://www.elastic.co/guide/en/ecctl/master/ecctl_stack_list.html).
     * 
     */
    private @Nullable List<String> plugins;
    /**
     * @return JSON-formatted user level `enterprise_search.yml` setting overrides.
     * 
     */
    private @Nullable String userSettingsJson;
    /**
     * @return JSON-formatted admin (ECE) level `enterprise_search.yml` setting overrides.
     * 
     */
    private @Nullable String userSettingsOverrideJson;
    /**
     * @return YAML-formatted admin (ECE) level `enterprise_search.yml` setting overrides.
     * 
     */
    private @Nullable String userSettingsOverrideYaml;
    /**
     * @return YAML-formatted user level `enterprise_search.yml` setting overrides.
     * 
     */
    private @Nullable String userSettingsYaml;

    private DeploymentElasticsearchTopologyConfig() {}
    /**
     * @return List of Elasticsearch supported plugins. Check the Stack Pack version to see which plugins are supported for each version. This is currently only available from the UI and [ecctl](https://www.elastic.co/guide/en/ecctl/master/ecctl_stack_list.html).
     * 
     */
    public List<String> plugins() {
        return this.plugins == null ? List.of() : this.plugins;
    }
    /**
     * @return JSON-formatted user level `enterprise_search.yml` setting overrides.
     * 
     */
    public Optional<String> userSettingsJson() {
        return Optional.ofNullable(this.userSettingsJson);
    }
    /**
     * @return JSON-formatted admin (ECE) level `enterprise_search.yml` setting overrides.
     * 
     */
    public Optional<String> userSettingsOverrideJson() {
        return Optional.ofNullable(this.userSettingsOverrideJson);
    }
    /**
     * @return YAML-formatted admin (ECE) level `enterprise_search.yml` setting overrides.
     * 
     */
    public Optional<String> userSettingsOverrideYaml() {
        return Optional.ofNullable(this.userSettingsOverrideYaml);
    }
    /**
     * @return YAML-formatted user level `enterprise_search.yml` setting overrides.
     * 
     */
    public Optional<String> userSettingsYaml() {
        return Optional.ofNullable(this.userSettingsYaml);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DeploymentElasticsearchTopologyConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> plugins;
        private @Nullable String userSettingsJson;
        private @Nullable String userSettingsOverrideJson;
        private @Nullable String userSettingsOverrideYaml;
        private @Nullable String userSettingsYaml;
        public Builder() {}
        public Builder(DeploymentElasticsearchTopologyConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.plugins = defaults.plugins;
    	      this.userSettingsJson = defaults.userSettingsJson;
    	      this.userSettingsOverrideJson = defaults.userSettingsOverrideJson;
    	      this.userSettingsOverrideYaml = defaults.userSettingsOverrideYaml;
    	      this.userSettingsYaml = defaults.userSettingsYaml;
        }

        @CustomType.Setter
        public Builder plugins(@Nullable List<String> plugins) {
            this.plugins = plugins;
            return this;
        }
        public Builder plugins(String... plugins) {
            return plugins(List.of(plugins));
        }
        @CustomType.Setter
        public Builder userSettingsJson(@Nullable String userSettingsJson) {
            this.userSettingsJson = userSettingsJson;
            return this;
        }
        @CustomType.Setter
        public Builder userSettingsOverrideJson(@Nullable String userSettingsOverrideJson) {
            this.userSettingsOverrideJson = userSettingsOverrideJson;
            return this;
        }
        @CustomType.Setter
        public Builder userSettingsOverrideYaml(@Nullable String userSettingsOverrideYaml) {
            this.userSettingsOverrideYaml = userSettingsOverrideYaml;
            return this;
        }
        @CustomType.Setter
        public Builder userSettingsYaml(@Nullable String userSettingsYaml) {
            this.userSettingsYaml = userSettingsYaml;
            return this;
        }
        public DeploymentElasticsearchTopologyConfig build() {
            final var o = new DeploymentElasticsearchTopologyConfig();
            o.plugins = plugins;
            o.userSettingsJson = userSettingsJson;
            o.userSettingsOverrideJson = userSettingsOverrideJson;
            o.userSettingsOverrideYaml = userSettingsOverrideYaml;
            o.userSettingsYaml = userSettingsYaml;
            return o;
        }
    }
}
