// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DeploymentElasticsearchRemoteCluster {
    /**
     * @return Alias for this Cross Cluster Search binding
     * 
     */
    private String alias;
    /**
     * @return Remote deployment ID
     * 
     */
    private String deploymentId;
    /**
     * @return Remote elasticsearch &#34;ref_id&#34;, it is best left to the default value
     * 
     */
    private @Nullable String refId;
    /**
     * @return If true, skip the cluster during search when disconnected
     * 
     */
    private @Nullable Boolean skipUnavailable;

    private DeploymentElasticsearchRemoteCluster() {}
    /**
     * @return Alias for this Cross Cluster Search binding
     * 
     */
    public String alias() {
        return this.alias;
    }
    /**
     * @return Remote deployment ID
     * 
     */
    public String deploymentId() {
        return this.deploymentId;
    }
    /**
     * @return Remote elasticsearch &#34;ref_id&#34;, it is best left to the default value
     * 
     */
    public Optional<String> refId() {
        return Optional.ofNullable(this.refId);
    }
    /**
     * @return If true, skip the cluster during search when disconnected
     * 
     */
    public Optional<Boolean> skipUnavailable() {
        return Optional.ofNullable(this.skipUnavailable);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DeploymentElasticsearchRemoteCluster defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String alias;
        private String deploymentId;
        private @Nullable String refId;
        private @Nullable Boolean skipUnavailable;
        public Builder() {}
        public Builder(DeploymentElasticsearchRemoteCluster defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.alias = defaults.alias;
    	      this.deploymentId = defaults.deploymentId;
    	      this.refId = defaults.refId;
    	      this.skipUnavailable = defaults.skipUnavailable;
        }

        @CustomType.Setter
        public Builder alias(String alias) {
            if (alias == null) {
              throw new MissingRequiredPropertyException("DeploymentElasticsearchRemoteCluster", "alias");
            }
            this.alias = alias;
            return this;
        }
        @CustomType.Setter
        public Builder deploymentId(String deploymentId) {
            if (deploymentId == null) {
              throw new MissingRequiredPropertyException("DeploymentElasticsearchRemoteCluster", "deploymentId");
            }
            this.deploymentId = deploymentId;
            return this;
        }
        @CustomType.Setter
        public Builder refId(@Nullable String refId) {

            this.refId = refId;
            return this;
        }
        @CustomType.Setter
        public Builder skipUnavailable(@Nullable Boolean skipUnavailable) {

            this.skipUnavailable = skipUnavailable;
            return this;
        }
        public DeploymentElasticsearchRemoteCluster build() {
            final var _resultValue = new DeploymentElasticsearchRemoteCluster();
            _resultValue.alias = alias;
            _resultValue.deploymentId = deploymentId;
            _resultValue.refId = refId;
            _resultValue.skipUnavailable = skipUnavailable;
            return _resultValue;
        }
    }
}
