// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAzurePrivatelinkEndpointResult {
    /**
     * @return The domain name to used in when configuring a private hosted zone in the VNet connection.
     * 
     */
    private String domainName;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String region;
    /**
     * @return The service alias to establish a connection to.
     * 
     */
    private String serviceAlias;

    private GetAzurePrivatelinkEndpointResult() {}
    /**
     * @return The domain name to used in when configuring a private hosted zone in the VNet connection.
     * 
     */
    public String domainName() {
        return this.domainName;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String region() {
        return this.region;
    }
    /**
     * @return The service alias to establish a connection to.
     * 
     */
    public String serviceAlias() {
        return this.serviceAlias;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAzurePrivatelinkEndpointResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domainName;
        private String id;
        private String region;
        private String serviceAlias;
        public Builder() {}
        public Builder(GetAzurePrivatelinkEndpointResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domainName = defaults.domainName;
    	      this.id = defaults.id;
    	      this.region = defaults.region;
    	      this.serviceAlias = defaults.serviceAlias;
        }

        @CustomType.Setter
        public Builder domainName(String domainName) {
            this.domainName = Objects.requireNonNull(domainName);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            this.region = Objects.requireNonNull(region);
            return this;
        }
        @CustomType.Setter
        public Builder serviceAlias(String serviceAlias) {
            this.serviceAlias = Objects.requireNonNull(serviceAlias);
            return this;
        }
        public GetAzurePrivatelinkEndpointResult build() {
            final var o = new GetAzurePrivatelinkEndpointResult();
            o.domainName = domainName;
            o.id = id;
            o.region = region;
            o.serviceAlias = serviceAlias;
            return o;
        }
    }
}
