// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDeploymentEnterpriseSearchTopology {
    /**
     * @return Controls the allocation of this topology element as well as allowed sizes and node_types. It needs to match the ID of an existing instance configuration.
     * 
     */
    private String instanceConfigurationId;
    /**
     * @return Defines whether this instance should run as application/API server.
     * 
     */
    private Boolean nodeTypeAppserver;
    /**
     * @return Defines whether this instance should run as connector.
     * 
     */
    private Boolean nodeTypeConnector;
    /**
     * @return Defines whether this instance should run as background worker.
     * 
     */
    private Boolean nodeTypeWorker;
    /**
     * @return Amount of &#34;size_resource&#34; in Gigabytes. For example &#34;4g&#34;.
     * 
     */
    private String size;
    /**
     * @return Type of resource (&#34;memory&#34; or &#34;storage&#34;)
     * 
     */
    private String sizeResource;
    /**
     * @return Number of zones in which nodes will be placed.
     * 
     */
    private Integer zoneCount;

    private GetDeploymentEnterpriseSearchTopology() {}
    /**
     * @return Controls the allocation of this topology element as well as allowed sizes and node_types. It needs to match the ID of an existing instance configuration.
     * 
     */
    public String instanceConfigurationId() {
        return this.instanceConfigurationId;
    }
    /**
     * @return Defines whether this instance should run as application/API server.
     * 
     */
    public Boolean nodeTypeAppserver() {
        return this.nodeTypeAppserver;
    }
    /**
     * @return Defines whether this instance should run as connector.
     * 
     */
    public Boolean nodeTypeConnector() {
        return this.nodeTypeConnector;
    }
    /**
     * @return Defines whether this instance should run as background worker.
     * 
     */
    public Boolean nodeTypeWorker() {
        return this.nodeTypeWorker;
    }
    /**
     * @return Amount of &#34;size_resource&#34; in Gigabytes. For example &#34;4g&#34;.
     * 
     */
    public String size() {
        return this.size;
    }
    /**
     * @return Type of resource (&#34;memory&#34; or &#34;storage&#34;)
     * 
     */
    public String sizeResource() {
        return this.sizeResource;
    }
    /**
     * @return Number of zones in which nodes will be placed.
     * 
     */
    public Integer zoneCount() {
        return this.zoneCount;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDeploymentEnterpriseSearchTopology defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String instanceConfigurationId;
        private Boolean nodeTypeAppserver;
        private Boolean nodeTypeConnector;
        private Boolean nodeTypeWorker;
        private String size;
        private String sizeResource;
        private Integer zoneCount;
        public Builder() {}
        public Builder(GetDeploymentEnterpriseSearchTopology defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.instanceConfigurationId = defaults.instanceConfigurationId;
    	      this.nodeTypeAppserver = defaults.nodeTypeAppserver;
    	      this.nodeTypeConnector = defaults.nodeTypeConnector;
    	      this.nodeTypeWorker = defaults.nodeTypeWorker;
    	      this.size = defaults.size;
    	      this.sizeResource = defaults.sizeResource;
    	      this.zoneCount = defaults.zoneCount;
        }

        @CustomType.Setter
        public Builder instanceConfigurationId(String instanceConfigurationId) {
            this.instanceConfigurationId = Objects.requireNonNull(instanceConfigurationId);
            return this;
        }
        @CustomType.Setter
        public Builder nodeTypeAppserver(Boolean nodeTypeAppserver) {
            this.nodeTypeAppserver = Objects.requireNonNull(nodeTypeAppserver);
            return this;
        }
        @CustomType.Setter
        public Builder nodeTypeConnector(Boolean nodeTypeConnector) {
            this.nodeTypeConnector = Objects.requireNonNull(nodeTypeConnector);
            return this;
        }
        @CustomType.Setter
        public Builder nodeTypeWorker(Boolean nodeTypeWorker) {
            this.nodeTypeWorker = Objects.requireNonNull(nodeTypeWorker);
            return this;
        }
        @CustomType.Setter
        public Builder size(String size) {
            this.size = Objects.requireNonNull(size);
            return this;
        }
        @CustomType.Setter
        public Builder sizeResource(String sizeResource) {
            this.sizeResource = Objects.requireNonNull(sizeResource);
            return this;
        }
        @CustomType.Setter
        public Builder zoneCount(Integer zoneCount) {
            this.zoneCount = Objects.requireNonNull(zoneCount);
            return this;
        }
        public GetDeploymentEnterpriseSearchTopology build() {
            final var o = new GetDeploymentEnterpriseSearchTopology();
            o.instanceConfigurationId = instanceConfigurationId;
            o.nodeTypeAppserver = nodeTypeAppserver;
            o.nodeTypeConnector = nodeTypeConnector;
            o.nodeTypeWorker = nodeTypeWorker;
            o.size = size;
            o.sizeResource = sizeResource;
            o.zoneCount = zoneCount;
            return o;
        }
    }
}
