// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ec.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.ec.outputs.GetTrafficFilterRuleset;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetTrafficFilterResult {
    /**
     * @return The id of the traffic filter to select.
     * 
     */
    private @Nullable String id;
    /**
     * @return The exact name of the traffic filter to select.
     * 
     */
    private @Nullable String name;
    /**
     * @return Region where the traffic filter is. For Elastic Cloud Enterprise (ECE) installations, use `ece-region`
     * 
     */
    private @Nullable String region;
    /**
     * @return An individual ruleset
     * 
     */
    private List<GetTrafficFilterRuleset> rulesets;

    private GetTrafficFilterResult() {}
    /**
     * @return The id of the traffic filter to select.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return The exact name of the traffic filter to select.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Region where the traffic filter is. For Elastic Cloud Enterprise (ECE) installations, use `ece-region`
     * 
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }
    /**
     * @return An individual ruleset
     * 
     */
    public List<GetTrafficFilterRuleset> rulesets() {
        return this.rulesets;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetTrafficFilterResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable String name;
        private @Nullable String region;
        private List<GetTrafficFilterRuleset> rulesets;
        public Builder() {}
        public Builder(GetTrafficFilterResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.region = defaults.region;
    	      this.rulesets = defaults.rulesets;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder region(@Nullable String region) {

            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder rulesets(List<GetTrafficFilterRuleset> rulesets) {
            if (rulesets == null) {
              throw new MissingRequiredPropertyException("GetTrafficFilterResult", "rulesets");
            }
            this.rulesets = rulesets;
            return this;
        }
        public Builder rulesets(GetTrafficFilterRuleset... rulesets) {
            return rulesets(List.of(rulesets));
        }
        public GetTrafficFilterResult build() {
            final var _resultValue = new GetTrafficFilterResult();
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.region = region;
            _resultValue.rulesets = rulesets;
            return _resultValue;
        }
    }
}
