// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Inputs
{

    public sealed class DeploymentTrafficFilterRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Azure endpoint GUID. Only applicable when the ruleset type is set to `azure_private_endpoint`
        /// </summary>
        [Input("azureEndpointGuid")]
        public Input<string>? AzureEndpointGuid { get; set; }

        /// <summary>
        /// Azure endpoint name. Only applicable when the ruleset type is set to `azure_private_endpoint`
        /// </summary>
        [Input("azureEndpointName")]
        public Input<string>? AzureEndpointName { get; set; }

        /// <summary>
        /// Description of this individual rule
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Computed rule ID
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Traffic filter source: IP address, CIDR mask, or VPC endpoint ID, **only required** when the type is not `azure_private_endpoint`
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        public DeploymentTrafficFilterRuleArgs()
        {
        }
        public static new DeploymentTrafficFilterRuleArgs Empty => new DeploymentTrafficFilterRuleArgs();
    }
}
