// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Inputs
{

    public sealed class DeploymentElasticsearchSnapshotRepositoryReferenceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("repositoryName", required: true)]
        public Input<string> RepositoryName { get; set; } = null!;

        public DeploymentElasticsearchSnapshotRepositoryReferenceGetArgs()
        {
        }
        public static new DeploymentElasticsearchSnapshotRepositoryReferenceGetArgs Empty => new DeploymentElasticsearchSnapshotRepositoryReferenceGetArgs();
    }
}
