// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Inputs
{

    public sealed class OrganizationMembersDeploymentRoleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Role applies to all deployments in the organization.
        /// </summary>
        [Input("allDeployments")]
        public Input<bool>? AllDeployments { get; set; }

        [Input("applicationRoles")]
        private InputList<string>? _applicationRoles;

        /// <summary>
        /// If provided, the user assigned this role assignment will be granted this application role when signing in to the deployment(s) specified in the role assignment.
        /// </summary>
        public InputList<string> ApplicationRoles
        {
            get => _applicationRoles ?? (_applicationRoles = new InputList<string>());
            set => _applicationRoles = value;
        }

        [Input("deploymentIds")]
        private InputList<string>? _deploymentIds;

        /// <summary>
        /// Role applies to deployments listed here.
        /// </summary>
        public InputList<string> DeploymentIds
        {
            get => _deploymentIds ?? (_deploymentIds = new InputList<string>());
            set => _deploymentIds = value;
        }

        /// <summary>
        /// Assigned role. Must be on of `Viewer`, `Editor` or `Admin`.
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        public OrganizationMembersDeploymentRoleGetArgs()
        {
        }
        public static new OrganizationMembersDeploymentRoleGetArgs Empty => new OrganizationMembersDeploymentRoleGetArgs();
    }
}
