// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Inputs
{

    public sealed class SecurityProjectSearchLakeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration to control the data retention in Elasticsearch data streams.
        /// </summary>
        [Input("dataRetention")]
        public Input<Inputs.SecurityProjectSearchLakeDataRetentionGetArgs>? DataRetention { get; set; }

        public SecurityProjectSearchLakeGetArgs()
        {
        }
        public static new SecurityProjectSearchLakeGetArgs Empty => new SecurityProjectSearchLakeGetArgs();
    }
}
