// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ElasticCloud.Inputs
{

    public sealed class ServerlessTrafficFilterRuleGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Description of the rule.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Allowed traffic filter source: IP address, CIDR mask, or VPC endpoint ID
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        public ServerlessTrafficFilterRuleGetArgs()
        {
        }
        public static new ServerlessTrafficFilterRuleGetArgs Empty => new ServerlessTrafficFilterRuleGetArgs();
    }
}
